medical_data:
  description: >
    You have the raw handwritten data : {statement} . 
    Your aim is to find the neccasary details like Medicine Names , dosage of the medicine and any precaution from the raw data.
    Present the extracted information in a clear, structured format. 
    Only include information explicitly present in the text and avoid adding assumptions.
    Focus on accuracy, clarity, and completeness.

  expected_output: >
    A fully structured and medical prescription in a consistent and english format,keeping the prescription small and direct containing:
      - List of recommended medicines
      - For how many days we have to take the specific medicine and in a particular day how many times we have to take it
      - precaution in taking the medicine like maximum consumption etc.

  agent: Medical_Data_Extractor
