medical_consultation:
  description: >
    Receive the patient's spoken or written statement about their symptoms in Hindi language: {statement}. 
    Retrieve the user's past medical history, allergies, and profile details from Crew memory (stored via ChromaDB) 
    to personalize the diagnosis and prescription.

    Based on both:
      (a) the reported symptoms, and 
      (b) the user's medical history and allergies,
    analyze the case thoroughly and generate a **safe, professional, and realistic medical prescription** in English.
    
  expected_output: >
    A fully structured and medical prescription in a consistent and english format,keeping the prescription small and direct containing:
      - Medicine List that is most suited to cure the symptoms and the name in the List should be as exact as it is on ecommerce platform
      - For how many days we have to take the specific medicine and in a particular day how many times we have to take it
      - precaution in taking the medicine like maximum consumption etc.
    
  agent: doctor
